### ISSUE TITLE
Error exit looking at serials

### ISSUE THREAD

**Issue by shane-kerr** [shane-kerr/soaping#2]
```
Traceback (most recent call last):
  File "soaping.py", line 605, in <module>
    main()
  File "soaping.py", line 593, in main
    curses.wrapper(ui, args.domain[0], cursesq)
  File "/opt/python3.6.1/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "soaping.py", line 511, in ui
    for serial in sorted(serials.keys()):
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by shane-kerr** [comment]
This should be fixed in commit f0f91fa43a6bca426924318697ef790c9b20ec49.
